### ISSUE TITLE
Visualizer improvement idea

### ISSUE THREAD

**Issue by jramhani** [packing-box/docker-packing-box#139]
## Comparison of the header

It would be nice to have also an option to view the comparison of the header of two files, for :
 `visualizer compare` 

Currently we cannot visualize header modifications with that visualization.

**Comment by dhondta** [comment]
Hi @jramhani !
Do you mean a comparison between two executables like with the [executable](https://github.com/packing-box/docker-packing-box/blob/main/src/files/tools/executable#L28) tool ? Can you be more precise ?

**Comment by jramhani** [comment]
For example if a alter something in the header like the checksum. I cannot see in the current plots visualizations.

![image](https://github.com/user-attachments/assets/d6afe19f-1405-4c92-a6a3-ba7a57743a91)

**Comment by jramhani** [comment]
PS: I misclicked, did not want to close the issue

**Comment by jramhani** [comment]
You're right , the modified line was small in the plot using `executable` so i did not see it. Thanks!
