### ISSUE TITLE
Alteration percentage can't be defined in the command-line

### ISSUE THREAD

**Issue by RomainJennes** [packing-box/docker-packing-box#30]
# Description
When altering a dataset with the `dataset alter` command, the option (`-p`) to set an alteration percentage is not handled correctly.
It works with the default value of 10%, but when the user tries to set another value, the tool alters 0% of the dataset.

From my own debugging, it seems that the command-line argument is handled incorrectly and that a `False` value is passed to `Dataset.alter` for the `percentage` argument.

# Output & steps to reproduce:
```console
$ dataset make test-upx -n 100 -f PE -p upx
$ dataset alter test-upx -p 0.8
00:00:04.980 [INFO] Altering 0% of the dataset...
```

**Comment by dhondta** [comment]
@RomainJennes you're right ; see the [`dataset` tool](https://github.com/packing-box/docker-packing-box/blob/main/src/files/tools/dataset#L54) : 
```python
    alter.add_argument("-p", "--percentage", type=ts.is_percentage, default=.1,
                       help="percentage of samples to be altered")
```
I use the `is_percentage` helper hence yielding a `True` which means `1.` or 100% each time the `-p` option is passed.
I'll fix this immediately.
Thank you.
