### ISSUE TITLE
Add dimensionality reduction parameters to exported image name. 

### ISSUE THREAD

**Issue by smarbal** [packing-box/docker-packing-box#53]
## Improvement suggestion
To make comparison between visualizations easier, it would be nice to have the PCA/t-SNE parameters in the name of the exported file. 
For now, visualizations with different parameters will have the same file name and a new visualization will overwrite the previous visualization.

**Comment by dhondta** [comment]
Hi @smarbal 
Good point. Can you provide an example of 2 such filenames ?

**Comment by smarbal** [comment]
For a file currently named `fs-upx_pe32-pe64_1909_kmeans_f15.png`, where : 
-  PCA has 20 components 
-  t-SNE has 2 components  

It could be interesting to have it named : `fs-upx_pe32-pe64_1909_kmeans_f15_p20_t2.png` . 

Having the perplexity parameter of t-SNE could also be interesting but could make the naming a bit confusing. 
Maybe having `fs-upx_pe32-pe64_1909_kmeans_f15_p20_t2-30.png` would be interesting, where 30 is the perplexity.

**Comment by dhondta** [comment]
@smarbal Please test.

**Comment by smarbal** [comment]
Works as intended. Thank you.
