### ISSUE TITLE
Introduce FastICA in dimensionality reduction techniques

### ISSUE THREAD

**Issue by smarbal** [packing-box/docker-packing-box#55]
### Improvement suggestion
Add an option to choose between PCA and ICA for dimensionality reduction when visualizing. 

#### Implementation
https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FastICA.html

**Comment by dhondta** [comment]
@smarbal This should be OK. Please test.

**Comment by smarbal** [comment]
This works fine. Thanks.
