### ISSUE TITLE
Introduce zone selection for visualization

### ISSUE THREAD

**Issue by smarbal** [packing-box/docker-packing-box#56]
### Improvement suggestion
Add an `x` and `y` coordinate selection in visualization to be able to focus on some clusters.

**Comment by dhondta** [comment]
@smarbal 
Please refine. What do you mean with _`x` and `y` coordinate selection_ ?

**Comment by smarbal** [comment]
In some plots, some small clusters are more interesting than the whole plot.
In order to focus on those clusters, it would be nice to be able to "crop" that zone by selecting `x` and `y` ranges that would then be plotted.
Sorry for the vagueness, I am currently working on the visualization so I'll implement it.

**Comment by dhondta** [comment]
@smarbal Cfr your PR #69 ; please update your code based on the current `main` branch to resolve this issue.

**Comment by dhondta** [comment]
Fixed by #69
