### ISSUE TITLE
Introduce logging of kept and not kept features

### ISSUE THREAD

**Issue by smarbal** [packing-box/docker-packing-box#57]
### Improvement 
When training a model, some features have no importance and are not kept. It would be nice to see which are in this case and which aren't, maybe in the `model show` tool.

**Comment by dhondta** [comment]
@smarbal enhancement done. For now, you can see the dropped features in the debug info while training a model with `model train` AND you can also find the list of dropped features in model's metadata (`[...]/[model_name]/metadata.json`).

**Comment by dhondta** [comment]
Please test.

**Comment by smarbal** [comment]
Works fine. Thanks.
